### ISSUE TITLE
Adapter bleibt rot.

### ISSUE THREAD

**Issue by Nickybroke** [MeisterTR/ioBroker.kress#10]
Hallo,
habe einen Kress KR113.
Haben diesen in mein Wlan und in die Kress APP integriert.
Aber in Iobroker bekomme ich den Adapter nicht grün.

Muss ich mich bei Worx anmelden ? So steht es ja quasi in der Doku?
Alle 3 Pukte der Instanz bleiben auf rot stehen.
LOG: 

kress.0 | 2020-11-02 11:58:25.079 | info | (26488) mower 0 selected
kress.0 | 2020-11-02 11:58:23.971 | info | (26488) starting. Version 2.5.5 in /opt/iobroker/node_modules/iobroker.kress, node: v12.18.4, js-controller: 3.1.6
host.raspberrypi | 2020-11-02 11:58:21.951 | info | instance system.adapter.kress.0 started with pid 26488
host.raspberrypi | 2020-11-02 11:58:21.911 | info | "system.adapter.kress.0" enabled

**Comment by MeisterTR** [comment]
Bitte auf den worx Adapter umsteigen

**Comment by MeisterTR** [comment]
Und dort kress auswählen und mit den kress Daten anmelden

**Comment by Nickybroke** [comment]
Vilen Dank für diese Blitzantwort. Damit geht es. Daumen hoch!
